### PR TITLE
libmikmod playback settings (wrap, fadeout, loop) exposed and made customizable by the user

### PR DESCRIPTION
**Pull request by xquiet**
Hi,
TMikMod works like a charm but, I wasn't able to setup custom playback settings like wrap, fadeout and loop (e.g. wrap was set equal true in SetModule method) thus I exposed them as properties and made them customizable on a per-resource basis (i.e. while loading a module as a stream, a file or an embedded resource).

I also exposed CommandLine arguments through the TMikMod constructor in case of need.

It properly works inside a small project built with C++Builder 10.3 Community Edition.

Kind regards

### CODE REVIEW

**Comment by Crayon2000** [comment]
Hello @xquiet, I want to tell you I have already merged your commit 552f58f (Updated MikMod to version 3.3.11.1) in the master branch.

I won't accept the the two other commits from this PR. There are a few reasons:

1. The whole code format was changed
2. I don't like the approach of adding new parameters to a lot of methods
3. There are errors, ie: `__property int Wrap` should be `bool`
4. If the Module does not wrap and it is completed, the CPU usage will be 100%
5. There is bad syntax or wrong doxygen comments, ie: `@param AWrap` when the param is `ALoop`

For these reasons I have started to do my own implementation in this branch:
https://github.com/Crayon2000/TMikMod/tree/new-properties

The code is not completed yet and I will do more tests this week. Your feedback will also be appreciated.

I really like your idea for this new feature. I hope you understand why this PR is rejected.

**Comment by xquiet** [comment]
Hi @Crayon2000 , I understand the reason and I perfectly agree with your points: what I need after all it's a working implementation and I know that the one I provided (that does its job) was quickly sketched and not properly reviewed.

I will try your implementation asap and I'll provide feedback.

Thanks for your time.

**Comment by Crayon2000** [comment]
Hello @xquiet, I just want to let you know that the code in my branch was brought back to the master branch.

**Comment by xquiet** [comment]
Hello @Crayon2000 , I already tested it from your branch a few days ago and it works smoothly.
Thanks for your efforts.

**Pull request closed without merging**
